const BASE_PATH = '/icons/';

const TECH_ICON_MAP: Record<string, string> = {
  'angular':                      `${BASE_PATH}angular.svg`,
  'typescript':                   `${BASE_PATH}typescript.svg`,
  'javascript':                   `${BASE_PATH}javascript.svg`,
  'js':                           `${BASE_PATH}javascript.svg`,
  'node.js':                      `${BASE_PATH}nodedotjs.svg`,
  'nodejs':                       `${BASE_PATH}nodedotjs.svg`,
  'node':                         `${BASE_PATH}nodedotjs.svg`,
  'react':                        `${BASE_PATH}react.svg`,
  'react.js':                     `${BASE_PATH}react.svg`,
  'vue':                          `${BASE_PATH}vuedotjs.svg`,
  'next.js':                      `${BASE_PATH}nextdotjs.svg`,
  'nextjs':                       `${BASE_PATH}nextdotjs.svg`,
  'html':                         `${BASE_PATH}html5.svg`,
  'html5':                        `${BASE_PATH}html5.svg`,
  'css':                          `${BASE_PATH}css.svg`,
  'css3':                         `${BASE_PATH}css.svg`,
  'html5/css3':                   `${BASE_PATH}html5.svg`,
  'sass':                         `${BASE_PATH}sass.svg`,
  'tailwind':                     `${BASE_PATH}tailwindcss.svg`,
  'tailwindcss':                  `${BASE_PATH}tailwindcss.svg`,
  'bootstrap':                    `${BASE_PATH}bootstrap.svg`,
  'python':                       `${BASE_PATH}python.svg`,
  'java':                         `${BASE_PATH}openjdk.svg`,
  'kotlin':                       `${BASE_PATH}kotlin.svg`,
  'android':                      `${BASE_PATH}android.svg`,
  'flutter':                      `${BASE_PATH}flutter.svg`,
  'dart':                         `${BASE_PATH}dart.svg`,
  'mysql':                        `${BASE_PATH}mysql.svg`,
  'sql':                          `${BASE_PATH}mysql.svg`,
  'postgres':                     `${BASE_PATH}postgresql.svg`,
  'postgresql':                   `${BASE_PATH}postgresql.svg`,
  'mongodb':                      `${BASE_PATH}mongodb.svg`,
  'redis':                        `${BASE_PATH}redis.svg`,
  'aws':                          `${BASE_PATH}mdi--aws.svg`,
  'docker':                       `${BASE_PATH}docker.svg`,
  'gcp':                          `${BASE_PATH}mdi--google-cloud.svg`,
  'azure':                        `${BASE_PATH}mdi--microsoft-azure.svg`,
  'firebase':                     `${BASE_PATH}firebase.svg`,
  'github':                       `${BASE_PATH}github.svg`,
  'git':                          `${BASE_PATH}git.svg`,
  'gitlab':                       `${BASE_PATH}gitlab.svg`,
  'linux':                        `${BASE_PATH}linux.svg`,
  'express':                      `${BASE_PATH}express.svg`,
  'express.js':                   `${BASE_PATH}express.svg`,
  'django':                       `${BASE_PATH}django.svg`,
  'flask':                        `${BASE_PATH}flask.svg`,
  'fastapi':                      `${BASE_PATH}fastapi.svg`,
  'spring':                       `${BASE_PATH}spring.svg`,
  'laravel':                      `${BASE_PATH}laravel.svg`,
  'php':                          `${BASE_PATH}php.svg`,
  'tensorflow':                   `${BASE_PATH}tensorflow.svg`,
  'pytorch':                      `${BASE_PATH}pytorch.svg`,
  'scikit-learn':                 `${BASE_PATH}scikitlearn.svg`,
  'pandas':                       `${BASE_PATH}pandas.svg`,
  'numpy':                        `${BASE_PATH}numpy.svg`,
  'openai':                       `${BASE_PATH}mingcute--openai-fill.svg`,
  'openai api':                   `${BASE_PATH}mingcute--openai-fill.svg`,
  'langchain':                    `${BASE_PATH}langchain.svg`,
  'llms':                         `${BASE_PATH}carbon--machine-learning-model.svg`,
  'rags':                         `${BASE_PATH}carbon--document-tasks.svg`,
  'llamaindex':                   `${BASE_PATH}lucide--bot-message-square.svg`,
  'machine learning':             `${BASE_PATH}carbon--machine-learning-model.svg`,
  'power bi':                     `${BASE_PATH}Power-BI.svg`,
  'groq cloud':                   `${BASE_PATH}mynaui--zap.svg`,
  'groq':                         `${BASE_PATH}mynaui--zap.svg`,
  'jmeter':                       `${BASE_PATH}apachejmeter.svg`,
  'loadrunner':                   `${BASE_PATH}carbon--test-tool.svg`,
  'postman':                      `${BASE_PATH}postman.svg`,
  'postman api':                  `${BASE_PATH}postman.svg`,
  'soapui':                       `${BASE_PATH}carbon--api-1.svg`,
  'alm':                          `${BASE_PATH}carbon--task-tools.svg`,
  'grafana':                      `${BASE_PATH}grafana.svg`,
  'influxdb':                     `${BASE_PATH}influxdb.svg`,
  'rest apis':                    `${BASE_PATH}openapiinitiative.svg`,
  'figma':                        `${BASE_PATH}figma.svg`,
  'three.js':                     `${BASE_PATH}threedotjs.svg`,
  'full stack':                   `${BASE_PATH}fullstack.svg`,
  'soft skills':                  `${BASE_PATH}softskills.svg`,
  'english as a second language': `${BASE_PATH}english.svg`,
  'testing':                      `${BASE_PATH}testing.svg`,
  'mariadb':                      `${BASE_PATH}mariadb.svg`,
  'cloudflare':                   `${BASE_PATH}cloudflare.svg`,
  'colab':                        `${BASE_PATH}googlecolab.svg`,
  'google colab':                 `${BASE_PATH}googlecolab.svg`,
  'googlecolab':                  `${BASE_PATH}googlecolab.svg`,
};

export function techIcon(rawTag: string): string {
  if (!rawTag) return '';
  return TECH_ICON_MAP[rawTag.trim().toLowerCase()] ?? '';
}

export function hideIconOnError(event: Event): void {
  (event.target as HTMLImageElement).style.display = 'none';
}